// This file is auto-generated by @hey-api/openapi-ts

export type GetApiHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/hello';
};

export type GetApiHelloResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTimeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/time';
};

export type GetApiTimeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiEchoData = {
    body?: never;
    path?: never;
    query: {
        message: string;
    };
    url: '/api/echo';
};

export type PostApiEchoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:7006' | (string & {});
};